//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Unit.Amazonia.DeliveryRoute.GridMap.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Unit.Amazonia.DeliveryRoute.GridMap.Resources.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;A1&quot;:{&quot;A2&quot;:11.88,&quot;B1&quot;:10.46},&quot;A2&quot;:{&quot;A3&quot;:22,&quot;B2&quot;:24.6,&quot;A1&quot;:21.77},&quot;A3&quot;:{&quot;A4&quot;:25.63,&quot;B3&quot;:12.66,&quot;A2&quot;:22.5},&quot;A4&quot;:{&quot;A5&quot;:27.69,&quot;B4&quot;:16.35,&quot;A3&quot;:15.5},&quot;A5&quot;:{&quot;A6&quot;:28.77,&quot;B5&quot;:18.45,&quot;A4&quot;:15.49},&quot;A6&quot;:{&quot;A7&quot;:23.72,&quot;B6&quot;:19.73,&quot;A5&quot;:25.55},&quot;A7&quot;:{&quot;A8&quot;:16.91,&quot;B7&quot;:27.97,&quot;A6&quot;:20.31},&quot;B1&quot;:{&quot;A1&quot;:23.01,&quot;B2&quot;:20.19,&quot;C1&quot;:15.37},&quot;B2&quot;:{&quot;A2&quot;:26.7,&quot;B3&quot;:29,&quot;C2&quot;:20.85,&quot;B1&quot;:13.88},&quot;B3&quot;:{&quot;A3&quot;:23.3,&quot;B4&quot;:20.27,&quot;C3&quot;:17.33,&quot;B2&quot;:18.72},&quot;B4&quot;:{&quot;A4&quot;:17.7,&quot;B5&quot;:18.32,&quot;C4&quot;:15.52,&quot;B3&quot;:10.5},&quot;B5&quot;:{&quot;A5&quot;:29.89,&quot;B6&quot;:11.89,&quot;C5&quot;:25.49,&quot;B4&quot;:25.79},&quot;B6&q....
        /// </summary>
        internal static string ValidGridJson {
            get {
                return ResourceManager.GetString("ValidGridJson", resourceCulture);
            }
        }
    }
}
